import DLL from "./DLL.js";

const testDLL = new DLL();
testDLL.append(456);
testDLL.append(567);
testDLL.append(6789);
testDLL.append(77);
testDLL.append(289);
testDLL.append(3000);
testDLL.prepend(22);
testDLL.prepend(123);
testDLL.prepend(88);
testDLL.prepend(54);
testDLL.prepend(9999);
testDLL.prepend(1000);
console.log("\n\t\t\t\t---- Default Printing ----\n");
console.log(testDLL.toString());
console.log("\n\t\t\t\t---- deleteHead() ----\n");
console.log("Delete Head 1:", testDLL.deleteHead());
console.log("Delete Head 2:", testDLL.deleteHead());
console.log("Delete Head 3:", testDLL.deleteHead());
console.log(testDLL.toString());
console.log("\n\t\t\t\t---- deleteTail() ----\n");
console.log("Delete Tail 1:", testDLL.deleteTail());
console.log("Delete Tail 2:", testDLL.deleteTail());
console.log("Delete Tail 3:", testDLL.deleteTail());
console.log(testDLL.toString());
console.log("\n\t\t\t\t---- reverseByPointer() ----\n");
testDLL.reverseByPointer();
console.log(testDLL.toString());
console.log("\n\t\t\t\t---- reverseByValue() ----\n");
testDLL.reverseByValue();
console.log(testDLL.toString());
